

name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t haider0946/edu-chatbot:latest .
        docker push haider0946/edu-chatbot:latest

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull haider0946/edu-chatbot:latest
          docker stop edu-chatbot || true
          docker rm edu-chatbot || true
          docker run -d --name edu-chatbot -p 80:8000 haider0946/edu-chatbot:latest
